apiVersion: training.eduk8s.io/v1alpha2
kind: Workshop
metadata:
  name: lab-carvel-kapp-controller-intro
spec:
  title: An Introduction to kapp-controller
  description: A workship on learning the fundamentals of Kubernetes package management with kapp-controller
  vendor: eduk8s.io
  difficulty: beginner
  duration: 15m
  url: https://github.com/danielhelfand/lab-carvel-kapp-controller-intro
  content:
    image: danielhelfand/lab-carvel-kapp-controller-intro
    #files: github.com/eduk8s/lab-markdown-sample
  session:
    namespaces:
      budget: small
    applications:
      terminal:
        enabled: true
        layout: split
      console:
        enabled: true
      editor:
        enabled: true
    objects:
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: Role
      metadata:
        name: kapp-controller-user-namespace
      rules:
      - apiGroups:
        - kappctrl.k14s.io
        - install.package.carvel.dev
        resources:
        - apps
        - installedpackages
        verbs:
        - get
        - list
        - create
        - delete
        - update
      - apiGroups: 
        - apps 
        - ""
        resources:
        - deployments
        - deployments.apps
        - services
        - configmaps
        verbs:
        - get
        - list
        - create
        - update
        - delete
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: RoleBinding
      metadata:
        name: kapp-controller-user-namespace-binding
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: Role
        name: kapp-controller-user-namespace
      subjects:
      - kind: ServiceAccount
        namespace: $(workshop_namespace)
        name: $(service_account)
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRole
      metadata:
        name: kapp-controller-user-cluster
      rules:
      - apiGroups:
        - install.package.carvel.dev
        - package.carvel.dev
        resources:
        - packagerepositories
        - packages
        verbs:
        - get
        - list
        - create
        - delete
        - update
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRoleBinding
      metadata:
        name: kapp-controller-user-cluster-binding
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: kapp-controller-user-cluster
      subjects:
      - kind: ServiceAccount
        namespace: $(workshop_namespace)
        name: $(service_account)
