apiVersion: v1
kind: ServiceAccount
metadata:
  name: simple-app-sa
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: simple-app-role
  annotations:
    kapp.k14s.io/change-group: "rbac.role"
rules:
- apiGroups: 
  - apps 
  - ""
  resources:
  - deployments
  - deployments.apps
  - services
  - configmaps
  verbs:
  - get
  - list
  - create
  - update
  - delete
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: simple-app-role-binding
  annotations:
    kapp.k14s.io/change-rule: "upsert after upserting rbac.role"
subjects:
- kind: ServiceAccount
  name: simple-app-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: simple-app-role